#!/usr/bin/env python
env = Environment(CXX = 'g++', CXXFLAGS = '-O2 -Wall -g')
conf = Configure(env)
#check for headers n stuff :D
if not conf.CheckCXXHeader('boost/lexical_cast.hpp'):
	print("Please install (lib)boost -> http://www.boost.org/")
	Exit(1)
env = conf.Finish()

libmotor = env.Clone()
libmotor.Library('motor', map(lambda x: "motor/" + x + ".cpp", Split("address buffer socket")))

client = env.Clone()
client.Program('server.cpp', LIBS=['motor'], LIBPATH='.', CPPPATH='.')

server = env.Clone()
client.Program('client.cpp', LIBS=['motor'], LIBPATH='.', CPPPATH='.')

