#!/usr/bin/env python
import os;
env = Environment(CXX = 'g++', CXXFLAGS = '-O0 -Wall -g --std=c++0x', LIBPATH='.', CPPPATH='.', ENV = {'PATH' : os.environ['PATH'], 'TERM' : os.environ['TERM'], 'HOME' : os.environ['HOME']})
conf = Configure(env)

if not conf.CheckLib('GL'):
	print("Please install (lib)gl, by either:\
			Linux:\
				getting mesa -> http://mesa3d.org and a fitting driver for your video card, or by directly downloading a driver from your graphics card vendor.\
			Windows:\
				downloading a driver from your video cards vendor.")
	Exit(1)
env = conf.Finish()

def splitter(folder, files):
	return map(lambda x: folder + x + ".cpp", files.split())

# -- libs --
libnetwork = env.Clone()
libnetwork.Library('network', splitter("network/", "address sendbuffer receivebuffer receivebuffermanager socket"))

libgraphics = env.Clone()
libgraphics.Library('graphics', splitter("graphics/", "window image textvertices chatlog cube shaderHelper camera") + ["lib/glew/glew.c"], LIBS=['GL', 'SDL', 'SDL_image'])

libinput = env.Clone()
libinput.Library('input', splitter("input/", "input"))

libtime = env.Clone()
libtime.Library('time', splitter("time/", "cooldown"))

libchat = env.Clone()
libchat.Library('chat', splitter("chat/", "message"))

#libstuff = env.Clone()
#libstuff.Library('stuff', splitter("graphics/", "cube"))
# -- ---- --

guiclient = env.Clone()
guiclient.Program('guiclient.cpp', LIBS=['network', 'graphics', 'GL', 'SDL', 'SDL_image', 'input', 'time', 'chat'])

server = env.Clone()
server.Program('server.cpp', LIBS=['network'])
